---
Son: Son
Daughter: Daughter
Head of Family: Head of Family
Wife: Wife
Servant: Servant
"-": "-"
Sister: Sister
Boarder: Boarder
Grand Son: Grand Son
Brother: Brother
Grand Daughter: Grand Daughter
Niece: Niece
Nephew: Nephew
Visitor: Visitor
Mother: Mother
Lodger: Lodger
Daughter in Law: Daughter in Law
Sister in Law: Sister in Law
Mother in Law: Mother in Law
Son in Law: Son in Law
Father: Father
Relative: Relative
Brother in Law: Brother in Law
Cousin: Cousin
Step Son: Step Son
Aunt: Aunt
Step Daughter: Step Daughter
Husband: Husband
Grand Child: Grand Child
Assistant: Assistant
Domestic Servant: Domestic Servant
Father in Law: Father in Law
Uncle: Uncle
Nurse: Nurse
Farm Servant: Farm Servant
Shop Assistant: Shop Assistant
Apprentice: Apprentice
Inmate: Inmate
Member of Community: Member of Community
Cook: Cook
House Keeper: House Keeper
Grand Niece: Grand Niece
Daughter in law: Daughter in Law
Grand Nephew: Grand Nephew
Grand Mother: Grand Mother
Governess: Governess
Nurse Child: Nurse Child
General Servant: Servant
Head of Family Father: Head of Family
Head of Family Husband: Head of Family
Head of Family Wife: Head of Family
son: Son
Grand son: Grand Son
Widow: Widow
Sister in law: Sister in Law
Head of House: Head of Family
Crew: Crew
Friend: Friend
Sister of Mercy: Sister of Mercy
Child: Child
"?": "?"
Mother in law: Mother in Law
Employee: Employee
Nun: Nun
None: None
Head of Family Mother: Head of Family
Son in law: Son in Law
Labourer: Labourer
daughter: Daughter
Clerk: Clerk
Cook Domestic Servant: Cook Domestic Servant
Housekeeper: House Keeper
General Servant Domestic: Domestic Servant
Maid: Maid
House Maid: Maid
Domestic: Domestic
Brother in law: Brother in Law
Step Mother: Step Mother
Grandson: Grand Son
Attendant: Attendant
Servant Domestic: Domestic Servant
Subject: Subject
Head of family: Head of Family
Relation: Relative
Sons Wife: Daughter in Law
Neice: Niece
Step Sister: Step Sister
Housemaid: Maid
Barmaid: Barmaid
Grand Father: Grand Father
Adopted Daughter: Adopted Daughter
Sister in Religion: Sister in Religion
Groom: Groom
Member: Member
Adopted Son: Adopted Son
Grand daughter: Grand Daughter
Members of Community: Member of Community
Scholar: Scholar
Nephew in Law: Nephew in Law
Sailor: Sailor
Companion: Companion
Grand Children: Grand Child
Step Brother: Step Brother
General Domestic Servant: Domestic Servant
Religious: Religious
Niece in Law: Niece in Law
wife: Wife
Son's Wife: Daughter in Law
Adopted Child: Adopted Child
Workman: Workman
Orphan: Orphan
Shopman: Shop Assistant
Adopted: Adopted Child
Hospital Nurse: Hospital Nurse
Milliner: Milliner
Laundress: Laundress
Teacher: Teacher
Matron: Matron
Parlour Maid: Parlour Maid
Aunt in Law: Aunt in Law
Farmers Son: Son
Coachman: Coachman
Father in law: Father in Law
Head of Family Son: Head of Family Son
Superior: Superior
Boarders: Boarder
'No': None
Inmate of Charity: Inmate of Charity
Manager: Manager
Baker: Baker
Wifes Mother: Mother in Law
No Relation: None
Inmate of Institution: Inmate of Institution
Great Grand Son: Great Grand Son
Half Sister: Half Sister
Shop Man: Shop Man
